[package]
name = "src"
version = "0.1.0"
edition = "2024"

[dependencies]

eframe = "0.24"
egui = "0.24"
iced = { version = "0.10", features = ["tokio"] }
tokio = { version = "1.0", features = ["full"] }
